url = "https://kyfw.12306.cn/otn/leftTicket/query?leftTicketDTO.train_date=2017-02-23&leftTicketDTO.from_station=BJP&leftTicketDTO.to_station=SHH&purpose_codes=ADULT"
content = requests.get(url, verify=False).text.encode("UTF-8")
jsonContent = json.loads(content)
for i in jsonContent["data"]:
    print "=" * 36
    print "始发站 : ", getStartStationName(i)
    print "终点站 : ", getEndStationName(i)
    print "起始站 : ", getFromStationName(i)
    print "到达站 : ", getToStationName(i)
    print "发车时间 : ", getStartTime(i)
    print "到达时间 : ", getArriveTime(i)
    print "其他 : ", getQitaNumber(i)
    print "无座 : ", getWuzuoNumber(i)
    print "硬座 : ", getYingzuoNumber(i)
    print "硬卧 : ", getYingwoNumber(i)
    print "软座 : ", getRuanzuoNumber(i)
    print "软卧 : ", getRuanwoNumber(i)
    print "高级软卧 : ", getGaojiruanwoNumber(i)
    print "二等座 : ", getYidengzuoNumber(i)
    print "一等座 : ", getErdengzuoNumber(i)
    print "特等座 : ", getTengdengzuoNumber(i)
    print "商务座 : ", getShangwuzuoNumber(i)
